import type { Metadata } from "next";
import "./globals.css";

// メタデータの設定（ページのタイトルなど）
export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <div className="flex justify-center items-center min-h-screen bg-gray-100">
          <div className="w-full max-w-[393px] min-h-screen bg-white flex flex-col mx-auto shadow-lg">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
